import { IEntitySchema } from "@drax/arch";

const SOURCE_CHANNELS = ["EMAIL", "FORWARDED_EMAIL", "MANUAL_UPLOAD", "API"];
const SENTIMENTS = ["POSITIVE", "NEUTRAL", "NEGATIVE", "MIXED"];
const URGENCIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const EXTRACTION_SOURCES = ["SUBJECT", "BODY", "ATTACHMENT", "MANUAL"];
const PROCESSING_STATUSES = [
    "PENDING",
    "PROCESSING",
    "PROCESSED",
    "REVIEW_REQUIRED",
    "REJECTED",
    "ERROR",
];
const REVIEW_STATUSES = ["PENDING", "APPROVED", "REJECTED", "CORRECTED"];

const entitySchema: IEntitySchema = {
    module: "mail",
    name: "InboundEmail",
    identifier: "messageId",
    apiBasePath: "inbound-emails",
    collectionName: "InboundEmail",
    apiTag: "mail",
    tabs: [
        "General",
        "Contenido",
        "Adjuntos",
        "Analisis IA",
        "Extraccion",
        "Procesamiento",
    ],
    schema: {
        messageId: {
            type: "string",
            required: true,
            unique: true,
            index: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        threadId: {
            type: "string",
            required: false,
            index: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        mailbox: {
            type: "string",
            required: false,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        sourceChannel: {
            type: "enum",
            enum: SOURCE_CHANNELS,
            required: true,
            default: "EMAIL",
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        receivedAt: {
            type: "date",
            required: true,
            index: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        subject: {
            type: "string",
            required: false,
            index: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        fromName: {
            type: "string",
            required: false,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        fromEmail: {
            type: "string",
            required: false,
            index: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        toEmails: {
            type: "array.string",
            required: false,
            groupTab: "General",
            mdCol: 12,
        },
        ccEmails: {
            type: "array.string",
            required: false,
            groupTab: "General",
            mdCol: 12,
        },
        replyToEmail: {
            type: "string",
            required: false,
            search: true,
            groupTab: "General",
            mdCol: 6,
        },
        bodyText: {
            type: "longString",
            required: false,
            search: true,
            groupTab: "Contenido",
            mdCol: 12,
        },
        bodyHtml: {
            type: "longString",
            required: false,
            groupTab: "Contenido",
            mdCol: 12,
        },
        normalizedText: {
            type: "longString",
            required: false,
            search: true,
            groupTab: "Contenido",
            mdCol: 12,
        },
        hasAttachments: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Contenido",
            mdCol: 4,
        },
        attachmentCount: {
            type: "number",
            required: false,
            default: 0,
            header: true,
            groupTab: "Contenido",
            mdCol: 4,
        },
        attachments: {
            type: "array.fullFile",
            required: false,
            groupTab: "Adjuntos",
            mdCol: 12,
        },
        category: {
            type: "string",
            required: false,
            index: true,
            search: true,
            header: true,
            groupTab: "Analisis IA",
            mdCol: 6,
        },
        sentiment: {
            type: "enum",
            enum: SENTIMENTS,
            required: false,
            header: true,
            groupTab: "Analisis IA",
            mdCol: 4,
        },
        urgency: {
            type: "enum",
            enum: URGENCIES,
            required: false,
            header: true,
            groupTab: "Analisis IA",
            mdCol: 4,
        },
        summary: {
            type: "longString",
            required: false,
            groupTab: "Analisis IA",
            mdCol: 12,
        },
        tags: {
            type: "array.string",
            required: false,
            groupTab: "Analisis IA",
            mdCol: 12,
        },
        aiModel: {
            type: "string",
            required: false,
            groupTab: "Analisis IA",
            mdCol: 6,
        },
        extractedData: {
            type: "object",
            required: false,
            groupTab: "Extraccion",
            schema: {
                affiliateName: {
                    type: "string",
                    required: false,
                    search: true,
                    header: true,
                    mdCol: 6,
                },
                affiliateDocumentNumber: {
                    type: "string",
                    required: false,
                    index: true,
                    search: true,
                    header: true,
                    mdCol: 6,
                },
                affiliateCuil: {
                    type: "string",
                    required: false,
                    index: true,
                    search: true,
                    header: true,
                    mdCol: 6,
                },
                affiliateEmail: {
                    type: "string",
                    required: false,
                    search: true,
                    mdCol: 4,
                },
                affiliatePhone: {
                    type: "string",
                    required: false,
                    search: true,
                    mdCol: 4,
                },
                affiliate: {
                    type: "ref",
                    ref: "Affiliate",
                    refDisplay: "fullName",
                    required: false,
                    mdCol: 12,
                },
                extractedEntities: {
                    type: "array.object",
                    required: false,
                    schema: {
                        label: {
                            type: "string",
                            required: true,
                            mdCol: 4,
                        },
                        value: {
                            type: "string",
                            required: false,
                            mdCol: 4,
                        },
                        source: {
                            type: "enum",
                            enum: EXTRACTION_SOURCES,
                            required: false,
                            mdCol: 4,
                        },
                        confidence: {
                            type: "number",
                            required: false,
                            mdCol: 4,
                        },
                    },
                },
            },
        },
        processingStatus: {
            type: "enum",
            enum: PROCESSING_STATUSES,
            required: true,
            default: "PENDING",
            index: true,
            header: true,
            groupTab: "Procesamiento",
            mdCol: 6,
        },
        reviewStatus: {
            type: "enum",
            enum: REVIEW_STATUSES,
            required: false,
            default: "PENDING",
            header: true,
            groupTab: "Procesamiento",
            mdCol: 6,
        },
        needsHumanReview: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Procesamiento",
            mdCol: 4,
        },
        autoApproved: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Procesamiento",
            mdCol: 4,
        },
        isDuplicate: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Procesamiento",
            mdCol: 4,
        },
        duplicateOfMessageId: {
            type: "string",
            required: false,
            index: true,
            search: true,
            groupTab: "Procesamiento",
            mdCol: 6,
        },
        rejectionReason: {
            type: "longString",
            required: false,
            groupTab: "Procesamiento",
            mdCol: 12,
        },
        validationNotes: {
            type: "longString",
            required: false,
            groupTab: "Procesamiento",
            mdCol: 12,
        },
        rawExtractionJson: {
            type: "longString",
            required: false,
            groupTab: "Procesamiento",
            mdCol: 12,
        },
        processedAt: {
            type: "date",
            required: false,
            groupTab: "Procesamiento",
            mdCol: 6,
        },
        lastErrorAt: {
            type: "date",
            required: false,
            groupTab: "Procesamiento",
            mdCol: 6,
        },
        lastErrorMessage: {
            type: "longString",
            required: false,
            groupTab: "Procesamiento",
            mdCol: 12,
        },
    },
};

export default entitySchema;
export { entitySchema };
