import { IEntitySchema } from "@drax/arch";

const MAIL_PROTOCOLS = ["IMAP", "POP"];

const MailboxSchema: IEntitySchema = {
    module: "mail",
    name: "Mailbox",
    identifier: "email",
    apiBasePath: "mailboxes",
    collectionName: "Mailbox",
    apiTag: "mail",
    tabs: ["General", "IMAP", "POP", "SMTP", "Procesamiento"],
    schema: {
        name: {
            type: "string",
            required: true,
            unique: true,
            index: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        email: {
            type: "string",
            required: true,
            unique: true,
            index: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        username: {
            type: "string",
            required: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        password: {
            type: "password",
            required: true,
            groupTab: "General",
            mdCol: 6,
        },
        isActive: {
            type: "boolean",
            required: false,
            default: true,
            header: true,
            groupTab: "General",
            mdCol: 3,
        },
        autoProcessEnabled: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Procesamiento",
            mdCol: 4,
        },
        processingProtocol: {
            type: "enum",
            enum: MAIL_PROTOCOLS,
            required: false,
            default: "IMAP",
            header: true,
            groupTab: "Procesamiento",
            mdCol: 4,
        },
        processingIntervalMinutes: {
            type: "number",
            required: false,
            default: 5,
            header: true,
            groupTab: "Procesamiento",
            mdCol: 4,
        },
        imapEnabled: {
            type: "boolean",
            required: false,
            default: true,
            header: true,
            groupTab: "IMAP",
            mdCol: 3,
        },
        imapHost: {
            type: "string",
            required: false,
            default: "mail.grupopremedic.com",
            search: true,
            header: true,
            groupTab: "IMAP",
            mdCol: 6,
        },
        imapPort: {
            type: "number",
            required: false,
            default: 993,
            header: true,
            groupTab: "IMAP",
            mdCol: 3,
        },
        imapTls: {
            type: "boolean",
            required: false,
            default: true,
            header: true,
            groupTab: "IMAP",
            mdCol: 3,
        },
        popEnabled: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "POP",
            mdCol: 3,
        },
        popHost: {
            type: "string",
            required: false,
            default: "mail.grupopremedic.com",
            search: true,
            groupTab: "POP",
            mdCol: 6,
        },
        popPort: {
            type: "number",
            required: false,
            default: 995,
            header: true,
            groupTab: "POP",
            mdCol: 3,
        },
        popTls: {
            type: "boolean",
            required: false,
            default: true,
            header: true,
            groupTab: "POP",
            mdCol: 3,
        },
        smtpEnabled: {
            type: "boolean",
            required: false,
            default: true,
            header: true,
            groupTab: "SMTP",
            mdCol: 3,
        },
        smtpHost: {
            type: "string",
            required: false,
            default: "mail.grupopremedic.com",
            search: true,
            header: true,
            groupTab: "SMTP",
            mdCol: 6,
        },
        smtpPort: {
            type: "number",
            required: false,
            default: 465,
            header: true,
            groupTab: "SMTP",
            mdCol: 3,
        },
        smtpTls: {
            type: "boolean",
            required: false,
            default: true,
            header: true,
            groupTab: "SMTP",
            mdCol: 3,
        },
    },
};

export default MailboxSchema;
export { MailboxSchema };
