import { IEntitySchema } from "@drax/arch";

const OUTBOUND_EMAIL_STATUSES = [
    "DRAFT",
    "QUEUED",
    "SENDING",
    "SENT",
    "FAILED",
    "CANCELLED",
];

const OutboundEmailSchema: IEntitySchema = {
    module: "mail",
    name: "OutboundEmail",
    identifier: "subject",
    apiBasePath: "outbound-emails",
    collectionName: "OutboundEmail",
    apiTag: "mail",
    tabs: ["General", "Destinatarios", "Contenido", "Envio"],
    schema: {
        inboundEmail: {
            type: "ref",
            ref: "InboundEmail",
            refDisplay: "messageId",
            required: true,
            index: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        mailbox: {
            type: "ref",
            ref: "Mailbox",
            refDisplay: "email",
            required: true,
            index: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        user: {
            type: "ref",
            ref: "User",
            refDisplay: "name",
            required: false,
            index: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        fromEmail: {
            type: "string",
            required: true,
            index: true,
            search: true,
            header: true,
            groupTab: "General",
            mdCol: 6,
        },
        toEmails: {
            type: "array.string",
            required: true,
            groupTab: "Destinatarios",
            mdCol: 12,
        },
        ccEmails: {
            type: "array.string",
            required: false,
            groupTab: "Destinatarios",
            mdCol: 12,
        },
        bccEmails: {
            type: "array.string",
            required: false,
            groupTab: "Destinatarios",
            mdCol: 12,
        },
        subject: {
            type: "string",
            required: true,
            index: true,
            search: true,
            header: true,
            groupTab: "Contenido",
            mdCol: 12,
        },
        bodyText: {
            type: "longString",
            required: false,
            search: true,
            groupTab: "Contenido",
            mdCol: 12,
        },
        bodyHtml: {
            type: "longString",
            required: false,
            groupTab: "Contenido",
            mdCol: 12,
        },
        status: {
            type: "enum",
            enum: OUTBOUND_EMAIL_STATUSES,
            required: true,
            default: "DRAFT",
            index: true,
            header: true,
            groupTab: "Envio",
            mdCol: 4,
        },
        messageId: {
            type: "string",
            required: false,
            index: true,
            search: true,
            header: true,
            groupTab: "Envio",
            mdCol: 8,
        },
        inReplyTo: {
            type: "string",
            required: false,
            index: true,
            search: true,
            groupTab: "Envio",
            mdCol: 6,
        },
        references: {
            type: "array.string",
            required: false,
            groupTab: "Envio",
            mdCol: 12,
        },
        sentAt: {
            type: "date",
            required: false,
            index: true,
            header: true,
            groupTab: "Envio",
            mdCol: 6,
        },
        lastError: {
            type: "longString",
            required: false,
            groupTab: "Envio",
            mdCol: 12,
        },
        attempts: {
            type: "number",
            required: false,
            default: 0,
            header: true,
            groupTab: "Envio",
            mdCol: 4,
        },
    },
};

export default OutboundEmailSchema;
export { OutboundEmailSchema };
